### ISSUE TITLE
node_modules should not be ignored by .gitignore

### ISSUE THREAD

**Issue by sirugh** [bazaarvoice/scoutfile#43]
Instead we should be using .npmignore to avoid publishing `node_modules` of scoutfile.

https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

As it is, users of this repo will have to manually check in scoutfile's node_modules.

**Comment by lawnsea** [comment]
This is by design: we didn't want `node_modules` to ever be checked into this repo, so we `.gitignore`d it. Note that `.npmignore`ing `node_modules` has no effect: 

> Additionally, everything in node_modules is ignored, except for bundled dependencies. npm automatically handles this for you, so don't bother adding node_modules to .npmignore.

What might work is to `.npmignore` the `.gitignore` file, with the result that `git add node_modules` will do the right thing.

**Comment by sirugh** [comment]
#44
