### ISSUE TITLE
Officially declare supported browsers

### ISSUE THREAD

**Issue by sirugh** [bazaarvoice/scoutfile#47]
We should decide on a minimum browser support level. I suggest IE9+.

**Comment by aterranova-bv** [comment]
[Based on this data](https://www.netmarketshare.com/browser-market-share.aspx?qprid=2&qpcustomd=0), As of September 2016, IE9 still has almost 5% market share so that seems good to me.

For completeness, IE8 does say 3.65% (though it was lower, to be honest), but I'd prefer to avoid the headaches.
