### ISSUE TITLE
Should the default timeout for `loadScript` be increased?

### ISSUE THREAD

**Issue by lawnsea** [bazaarvoice/scoutfile#9]
Under some circumstances (large file or slow connection, e.g.) it may be normal for a script to take more than 1000ms to download. Should we increase the default to something like five or 10 seconds?

**Comment by rmurphey** [comment]
What if by default there was no timeout, but consumer applications could choose to provide one?

**Comment by sirugh** [comment]
https://github.com/bazaarvoice/firebird/pull/5474

**Comment by aterranova-bv** [comment]
@sirugh can we close this issue now?

**Comment by sirugh** [comment]
Closed in #32
